export const groups = [
  {
    id: "characters",
    name: "Characters",
    short: "Character art",
    desc: "Stylized identities. Unmistakable silhouettes.",
    color: "#a6ffcb",
  },
  {
    id: "creatures",
    name: "Creatures",
    short: "Creature design",
    desc: "Wild anatomy. Worlds beyond the familiar.",
    color: "#b8a2ff",
  },
  {
    id: "roblox",
    name: "Roblox UGC",
    short: "Avatars & UGC",
    desc: "Expressive characters made for play.",
    color: "#ffe19c",
  },
  {
    id: "props",
    name: "Props & Weapons",
    short: "Props & weapons",
    desc: "Small details. Entire worlds.",
    color: "#ffab83",
  },
  {
    id: "motion",
    name: "Rigging & Motion",
    short: "Rigging & motion",
    desc: "From static form to living character.",
    color: "#ff90c9",
  },
  {
    id: "environments",
    name: "Environments",
    short: "Environment art",
    desc: "Spaces built for real-time exploration.",
    color: "#8fd7c9",
  },
  {
    id: "vfx",
    name: "VFX Studies",
    short: "Visual effects",
    desc: "Procedural motion and cinematic effects.",
    color: "#f2a6bd",
  },
  {
    id: "unity",
    name: "Unity Projects",
    short: "Real-time projects",
    desc: "Art in motion. Inside the engine.",
    color: "#91dbff",
  },
];
export const artworks = [
  {
    id: 0,
    group: "characters",
    title: "Scarlet",
    src: "assets/work/char-scarlet.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 1,
    group: "characters",
    title: "Mio",
    src: "assets/work/04.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 2,
    group: "characters",
    title: "Nocturne Seraph",
    src: "assets/work/char-seraph.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 3,
    group: "characters",
    title: "Naihe",
    src: "assets/work/06.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 4,
    group: "characters",
    title: "Valkyrie",
    src: "assets/work/cyber-valkyrie.jpg",
    tags: "Cyberpunk",
    type: "image",
  },
  {
    id: 5,
    group: "characters",
    title: "Valkyrie",
    src: "assets/work/08.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 6,
    group: "characters",
    title: "Naihe",
    src: "assets/work/cyber-naihe.jpg",
    tags: "Cyberpunk",
    type: "image",
  },
  {
    id: 7,
    group: "characters",
    title: "Oni Maiden",
    src: "assets/work/char-oni.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 8,
    group: "characters",
    title: "Nami",
    src: "assets/work/05.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 9,
    group: "characters",
    title: "Athan",
    src: "assets/work/cyber-athan.jpg",
    tags: "Cyberpunk",
    type: "image",
  },
  {
    id: 10,
    group: "characters",
    title: "Kriger",
    src: "assets/work/07.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 11,
    group: "characters",
    title: "Xinyun",
    src: "assets/work/cyber-xinyun.jpg",
    tags: "Cyberpunk",
    type: "image",
  },
  {
    id: 12,
    group: "characters",
    title: "Xinyun",
    src: "assets/work/09.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 13,
    group: "characters",
    title: "Vermilion Knight",
    src: "assets/work/char-vermilion.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 14,
    group: "characters",
    title: "Athan",
    src: "assets/work/10.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 15,
    group: "characters",
    title: "Kriger",
    src: "assets/work/cyber-kriger.jpg",
    tags: "Cyberpunk",
    type: "image",
  },
  {
    id: 16,
    group: "characters",
    title: "Jindoe",
    src: "assets/work/11.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 17,
    group: "characters",
    title: "3D Character",
    src: "assets/work/12.jpg",
    tags: "Real-time",
    type: "image",
  },
  {
    id: 18,
    group: "characters",
    title: "Aurora Seraph",
    src: "assets/work/char-aurora.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 19,
    group: "characters",
    title: "Jade Cultivator",
    src: "assets/work/char-jade.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 20,
    group: "characters",
    title: "Solar Warden",
    src: "assets/work/char-solar.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 21,
    group: "characters",
    title: "Divine Oni",
    src: "assets/work/char-divineoni.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 22,
    group: "characters",
    title: "Tribal Huntress",
    src: "assets/work/char-tribal.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 23,
    group: "characters",
    title: "Street Casual",
    src: "assets/work/char-casual.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 24,
    group: "characters",
    title: "Cleric",
    src: "assets/work/char-cleric.jpg",
    tags: "Stylized",
    type: "image",
  },
  {
    id: 25,
    group: "characters",
    title: "Neon Valkyrie",
    src: "assets/work/char-cybergirl.png",
    tags: "Cyberpunk",
    type: "image",
  },
  {
    id: 26,
    group: "roblox",
    title: "Golden Stand",
    src: "assets/work/roblox-golden-stand.png",
    tags: "Character",
    type: "image",
  },
  {
    id: 27,
    group: "roblox",
    title: "DIO",
    src: "assets/work/roblox-dio.png",
    tags: "Character",
    type: "image",
  },
  {
    id: 28,
    group: "roblox",
    title: "Silver Guardian",
    src: "assets/work/roblox-silver-guardian.png",
    tags: "Character",
    type: "image",
  },
  {
    id: 29,
    group: "roblox",
    title: "Eagle Warrior",
    src: "assets/work/roblox-eagle.png",
    tags: "UGC Bundle",
    type: "image",
  },
  {
    id: 30,
    group: "roblox",
    title: "Stone King",
    src: "assets/work/roblox-stone-king.png",
    tags: "Character",
    type: "image",
  },
  {
    id: 31,
    group: "roblox",
    title: "Silver Sentinel",
    src: "assets/work/roblox-silver-sentinel.png",
    tags: "Character",
    type: "image",
  },
  {
    id: 32,
    group: "roblox",
    title: "Cyber Guardian",
    src: "assets/work/roblox-cyber-guardian.png",
    tags: "Character",
    type: "image",
  },
  {
    id: 33,
    group: "roblox",
    title: "Purple Emperor",
    src: "assets/work/roblox-purple-emperor.png",
    tags: "Character",
    type: "image",
  },
  {
    id: 34,
    group: "roblox",
    title: "Golden Titan",
    src: "assets/work/roblox-golden-titan.png",
    tags: "Character",
    type: "image",
  },
  {
    id: 35,
    group: "roblox",
    title: "Crimson Fighter",
    src: "assets/work/roblox-crimson.png",
    tags: "Character",
    type: "image",
  },
  {
    id: 36,
    group: "roblox",
    title: "Spike Emperor",
    src: "assets/work/roblox-spike-emperor.png",
    tags: "Character",
    type: "image",
  },
  {
    id: 37,
    group: "roblox",
    title: "Golden World",
    src: "assets/work/roblox-golden-world.png",
    tags: "Character",
    type: "image",
  },
  {
    id: 38,
    group: "roblox",
    title: "Azure Stand",
    src: "assets/work/roblox-azure.png",
    tags: "Character",
    type: "image",
  },
  {
    id: 39,
    group: "roblox",
    title: "Outfit",
    src: "assets/work/item-outfit.png",
    tags: "UGC Clothing",
    type: "image",
  },
  {
    id: 40,
    group: "roblox",
    title: "Cat Plush",
    src: "assets/work/creature-cat-plush.png",
    tags: "UGC Item",
    type: "image",
  },
  {
    id: 41,
    group: "props",
    title: "Stylized Weapon Pack",
    src: "assets/work/weapon-pack.png",
    tags: "Game-Ready",
    type: "image",
  },
  {
    id: 42,
    group: "props",
    title: "Voidfang Dagger",
    src: "assets/work/01.jpg",
    tags: "Hard-Surface",
    type: "image",
  },
  {
    id: 43,
    group: "props",
    title: "Rune Sword",
    src: "assets/work/02.jpg",
    tags: "Hard-Surface",
    type: "image",
  },
  {
    id: 44,
    group: "props",
    title: "Wood Sword",
    src: "assets/work/03.jpg",
    tags: "Prop",
    type: "image",
  },
  {
    id: 45,
    group: "creatures",
    title: "Cyborg Bear",
    src: "assets/work/cyborg-bear.png",
    tags: "Creature",
    type: "image",
  },
  {
    id: 46,
    group: "creatures",
    title: "Mecha Hounds",
    src: "assets/work/mecha-hounds.png",
    tags: "Creature · Unity",
    type: "image",
  },
  {
    id: 47,
    group: "creatures",
    title: "Kuromi",
    src: "assets/work/kuromi.png",
    tags: "Stylized · Fanart",
    type: "image",
  },
  {
    id: 48,
    group: "creatures",
    title: "Rat",
    src: "assets/work/creature-rat.png",
    tags: "Creature",
    type: "image",
  },
  {
    id: 49,
    group: "motion",
    title: "Puppy",
    src: "assets/work/creature-dog.png",
    tags: "Creature · Rig",
    type: "image",
  },
  {
    id: 50,
    group: "motion",
    title: "Rat",
    src: "assets/work/creature-rat-rig.png",
    tags: "Creature · Rig",
    type: "image",
  },
  {
    id: 51,
    group: "motion",
    title: "Cyborg Bear",
    src: "assets/work/rig-cyborg-bear.png",
    tags: "Creature · Rig",
    type: "image",
  },
  {
    id: 52,
    group: "motion",
    title: "Centaur",
    src: "assets/work/rig-centaur.png",
    tags: "Creature · Rig",
    type: "image",
  },
  {
    id: 53,
    group: "motion",
    title: "Oni Rider",
    src: "assets/work/rig-oni-mount.png",
    tags: "Creature · Rig",
    type: "image",
  },
  {
    id: 54,
    group: "motion",
    title: "Mech Core",
    src: "assets/work/rig-mech-core.png",
    tags: "Mechanical · Rig",
    type: "image",
  },
  {
    id: 55,
    group: "motion",
    title: "Mech Core",
    src: "assets/work/rig-mech-core2.png",
    tags: "Mechanical · Rig",
    type: "image",
  },
  {
    id: 56,
    group: "characters",
    title: "DIO — Character turnaround",
    src: "assets/work/dio-turnaround.png",
    tags: "Character turnaround",
    type: "image",
  },
  {
    id: 57,
    group: "creatures",
    title: "Crimson Wyvern — Creature Study",
    src: "assets/work/crimson-dragon-flight.webp",
    tags: "Creature study",
    type: "image",
  },
  {
    id: 58,
    group: "creatures",
    title: "Crimson Wyvern — Front View",
    src: "assets/work/crimson-dragon-front.webp",
    tags: "Creature study",
    type: "image",
  },
  {
    id: 61,
    group: "creatures",
    title: "Crimson Wyvern — Profile Process",
    src: "assets/work/crimson-dragon-process-b.jpg",
    tags: "Creature study",
    type: "image",
  },
  {
    id: 62,
    group: "creatures",
    title: "Crimson Wyvern — Wing Process",
    src: "assets/work/crimson-dragon-process-c.jpg",
    tags: "Creature study",
    type: "image",
  },
  {
    id: 63,
    group: "creatures",
    title: "Watcher Beast — Creature Sheet",
    src: "assets/work/eye-tail-creature-sheet.jpg",
    tags: "Creature study",
    type: "image",
  },
  {
    id: 64,
    group: "props",
    title: "Rokaka Bloom — Fantasy Flora",
    src: "assets/work/fantasy-rokaka-bloom.webp",
    tags: "Fantasy flora",
    type: "image",
  },
  {
    id: 65,
    group: "motion",
    title: "Character Rig",
    src: "assets/work/rig-character.png",
    tags: "Rigging study",
    type: "image",
  },
  {
    id: 66,
    group: "motion",
    title: "Oni Maiden — Rig",
    src: "assets/work/rig-oni.png",
    tags: "Rigging study",
    type: "image",
  },
  {
    id: 67,
    group: "motion",
    title: "Serpent · Animation Study",
    src: "assets/video/serpent-animation-showcase.mp4",
    tags: "Animation study",
    type: "video",
  },
  {
    id: 68,
    group: "motion",
    title: "Serpent · Rig Controls",
    src: "assets/video/serpent-rig-showcase.mp4",
    tags: "Animation study",
    type: "video",
  },
  {
    id: 69,
    group: "motion",
    title: "Anime Character · Motion",
    src: "assets/video/anime-character-animation.mp4",
    tags: "Animation study",
    type: "video",
  },
  {
    id: 70,
    group: "motion",
    title: "Horse · Animation Front",
    src: "assets/video/horse-animation-front.mp4",
    tags: "Animation study",
    type: "video",
  },
  {
    id: 71,
    group: "motion",
    title: "Horse · Animation Back",
    src: "assets/video/horse-animation-back.mp4",
    tags: "Animation study",
    type: "video",
  },
  {
    id: 72,
    group: "motion",
    title: "Naihe",
    src: "assets/video/naihe.mp4",
    tags: "Character · Turntable",
    type: "video",
  },
  {
    id: 73,
    group: "motion",
    title: "Kriger",
    src: "assets/video/kriger.mp4",
    tags: "Character · Turntable",
    type: "video",
  },
  {
    id: 74,
    group: "motion",
    title: "Valkyrie",
    src: "assets/video/valkyrie.mp4",
    tags: "Character · Turntable",
    type: "video",
  },
  {
    id: 75,
    group: "motion",
    title: "Xinyun",
    src: "assets/video/xinyun.mp4",
    tags: "Character · Turntable",
    type: "video",
  },
  {
    id: 76,
    group: "motion",
    title: "Athan",
    src: "assets/video/athan.mp4",
    tags: "Character · Turntable",
    type: "video",
  },
  {
    id: 77,
    group: "motion",
    title: "Naihe · Cyberpunk",
    src: "assets/video/naihe-cyberpunk.mp4",
    tags: "Character · Turntable",
    type: "video",
  },
  {
    id: 78,
    group: "motion",
    title: "Nocturne Seraph",
    src: "assets/video/turn-seraph.mp4",
    tags: "Character · Turntable",
    type: "video",
  },
  {
    id: 79,
    group: "motion",
    title: "Freya",
    src: "assets/video/turn-freya.mp4",
    tags: "Character · Turntable",
    type: "video",
  },
  {
    id: 80,
    group: "motion",
    title: "Blender Rig & Animation",
    src: "assets/video/rig-blender.mp4",
    tags: "Rigging · Production",
    type: "video",
  },
  {
    id: 81,
    group: "motion",
    title: "Character Rig — Client Work",
    src: "assets/video/rig-client.mp4",
    tags: "Rigging · Production",
    type: "video",
  },
  {
    id: 82,
    group: "motion",
    title: "Live VTuber Tracking · VSeeFace",
    src: "assets/video/rig-vseeface.mp4",
    tags: "Rigging · Production",
    type: "video",
  },
  {
    id: 83,
    group: "motion",
    title: "Cleric — Rig",
    src: "assets/video/rig-cleric.mp4",
    tags: "Rigging · Production",
    type: "video",
  },
  {
    id: 84,
    group: "motion",
    title: "Character Pose & Rig",
    src: "assets/video/rig-casual.mp4",
    tags: "Rigging · Production",
    type: "video",
  },
  {
    id: 85,
    group: "motion",
    title: "Outfit — Client Work",
    src: "assets/video/rig-outfit.mp4",
    tags: "Rigging · Production",
    type: "video",
  },
  {
    id: 86,
    group: "motion",
    title: "ShikiChoco — VTuber Rig",
    src: "assets/video/rig-shikichoco.mp4",
    tags: "Rigging · Production",
    type: "video",
  },
  {
    id: 87,
    group: "motion",
    title: "Base Character Setup",
    src: "assets/video/rig-nel05.mp4",
    tags: "Rigging · Production",
    type: "video",
  },
  {
    id: 88,
    group: "motion",
    title: "Methira — Animation",
    src: "assets/video/rig-methira2.mp4",
    tags: "Rigging · Production",
    type: "video",
  },
  {
    id: 89,
    group: "motion",
    title: "Combat Drone — Rig & Animation",
    src: "assets/video/rig-mech-5.mp4",
    tags: "Rigging · Production",
    type: "video",
  },
  {
    id: 90,
    group: "motion",
    title: "Mechanical Rig — Deploy",
    src: "assets/video/rig-mech-4.mp4",
    tags: "Rigging · Production",
    type: "video",
  },
  {
    id: 91,
    group: "motion",
    title: "Mechanical Core — Open",
    src: "assets/video/rig-mech-3.mp4",
    tags: "Rigging · Production",
    type: "video",
  },
  {
    id: 92,
    group: "motion",
    title: "Mechanical Rig — Transform",
    src: "assets/video/rig-mech-2.mp4",
    tags: "Rigging · Production",
    type: "video",
  },
  {
    id: 93,
    group: "motion",
    title: "Mechanical Rig — Idle",
    src: "assets/video/rig-mech-1.mp4",
    tags: "Rigging · Production",
    type: "video",
  },
  {
    id: 94,
    group: "unity",
    title: "Avatar Animation · Unity",
    src: "assets/video/unity-3.mp4",
    tags: "Unity · Real-time",
    type: "video",
  },
  {
    id: 95,
    group: "unity",
    title: "Idle Dance · Unity",
    src: "assets/video/unity-4.mp4",
    tags: "Unity · Real-time",
    type: "video",
  },
  {
    id: 96,
    group: "unity",
    title: "Avatar Test · Unity",
    src: "assets/video/unity-5.mp4",
    tags: "Unity · Real-time",
    type: "video",
  },
  {
    id: 97,
    group: "unity",
    title: "VTuber Scene · Unity",
    src: "assets/video/unity-2.mp4",
    tags: "Unity · Real-time",
    type: "video",
  },
  {
    id: 98,
    group: "unity",
    title: "Avatar Showcase · Unity",
    src: "assets/video/unity-6.mp4",
    tags: "Unity · Real-time",
    type: "video",
  },
  {
    id: 99,
    group: "unity",
    title: "Scene Test · Unity",
    src: "assets/video/unity-7.mp4",
    tags: "Unity · Real-time",
    type: "video",
  },
  {
    id: 100,
    group: "motion",
    title: "Solar Sentinel - Rigify Rig",
    src: "assets/work/new-rig-solar-sentinel.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 101,
    group: "motion",
    title: "Luna Sentinel - Rigify Rig",
    src: "assets/work/new-rig-luna-sentinel.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 102,
    group: "motion",
    title: "Okami - Rigify Rig",
    src: "assets/work/new-rig-okami.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 103,
    group: "motion",
    title: "Kuro Okami - Rigify Rig",
    src: "assets/work/new-rig-kuro-okami.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 104,
    group: "motion",
    title: "Kaze - Rigify Rig",
    src: "assets/work/new-rig-kaze.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 105,
    group: "motion",
    title: "Kuma - Rigify Rig",
    src: "assets/work/new-rig-kuma.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 106,
    group: "motion",
    title: "Armor Kuma - Rigify Rig",
    src: "assets/work/new-rig-armor-kuma.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 107,
    group: "motion",
    title: "Yagi - Rigify Rig",
    src: "assets/work/new-rig-yagi.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 108,
    group: "motion",
    title: "Antler - Rigify Rig",
    src: "assets/work/new-rig-antler.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 109,
    group: "motion",
    title: "Crystal - Rigify Rig",
    src: "assets/work/new-rig-crystal.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 110,
    group: "motion",
    title: "Ancient Dragon - Rigify Rig",
    src: "assets/work/new-rig-ancient-dragon.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 111,
    group: "motion",
    title: "Phoenix - Rigify Rig",
    src: "assets/work/new-rig-phoenix.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 112,
    group: "motion",
    title: "Wicked - Rigify Rig",
    src: "assets/work/new-rig-wicked.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 113,
    group: "motion",
    title: "Wicked Spider - Rigify Rig",
    src: "assets/work/new-rig-wicked-spider.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 114,
    group: "motion",
    title: "Strange Bird - Rigify Rig",
    src: "assets/work/new-rig-strange-bird.jpg",
    tags: "Creature rigging / Weight painting / IK & FK",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 115,
    group: "motion",
    title: "Wicked Spider - Idle",
    src: "assets/video/new-wicked-spider-idle.mp4",
    tags: "Creature animation / Idle loop",
    type: "video",
    added: "2026-10-04",
  },
  {
    id: 120,
    group: "roblox",
    title: "Frog - Avatar Setup",
    src: "assets/work/new-frog-avatar.jpg",
    tags: "Avatar rigging / Facial controls / Blender",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 123,
    group: "vfx",
    title: "Multiverse - Timeline Collapse",
    src: "assets/work/new-multiverse-collapse.jpg",
    tags: "Blender VFX / Procedural filaments / Work in progress",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 124,
    group: "environments",
    title: "Training Ground - Environment",
    src: "assets/work/new-training-ground.jpg",
    tags: "Blender environment / PGR-inspired study",
    type: "image",
    added: "2026-10-04",
  },
  {
    id: 125,
    group: "environments",
    title: "Training Ground - Roblox",
    src: "assets/work/new-training-ground-roblox.jpg",
    tags: "Environment implementation / Animated grid / Roblox",
    type: "image",
    added: "2026-10-04",
  },
];
